# Generated by Django 4.0 on 2022-01-03 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, null=True)),
                ('messages', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='UserChatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.BinaryField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to='auth.user')),
            ],
        ),
    ]
