# Generated by Django 4.0 on 2022-01-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomprofile',
            name='messages',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userchatprofile',
            name='rooms',
            field=models.BinaryField(null=True),
        ),
    ]
