# Generated by Django 4.0 on 2022-01-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroomprofile_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatprofile',
            name='rooms_unread_messages',
            field=models.BinaryField(null=True),
        ),
    ]
