# Generated by Django 4.0 on 2022-01-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userchatprofile_rooms_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomprofile',
            name='room_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
