# Generated by Django 4.0 on 2022-01-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroomprofile_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchatprofile',
            old_name='rooms_unread_messages',
            new_name='rooms_timestamp',
        ),
    ]
