# Generated by Django 4.0 on 2022-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_rooms_unread_messages_userchatprofile_rooms_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomprofile',
            name='unread_message_count',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
