# Generated by Django 4.0 on 2022-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroomprofile_unread_message_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomprofile',
            name='unread_message_count',
            field=models.IntegerField(default=0),
        ),
    ]
