# Generated by Django 4.0 on 2022-01-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatroomprofile_unread_message_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroomprofile',
            name='unread_message_count',
        ),
    ]
