# Generated by Django 4.0 on 2022-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chatroomprofile_unread_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatprofile',
            name='last_seen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
